// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FlashcardController from "./flashcard_controller"
application.register("flashcard", FlashcardController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)
